
// const button = document.getElementById('btn');

const topic = document.getElementById('topic');


// topics 

const topicsArray = [
    "Artificial Intelligence and Machine Learning",
    "Cybersecurity and Data Privacy",
    "Blockchain Technology",
    "Quantum Computing",
    "Internet of Things (IoT)",
    "Cloud Computing",
    "Big Data Analytics",
    "Augmented Reality (AR) and Virtual Reality (VR)",
    "Natural Language Processing (NLP)",
    "Robotics and Automation",
    "Software Development Methodologies (Agile, Scrum, etc.)",
    "DevOps Practices",
    "Continuous Integration and Continuous Deployment (CI/CD)",
    "Web Development Trends",
    "Mobile App Development",
    "Cross-platform Development",
    "Programming Languages (Python, Java, JavaScript, etc.)",
    "Open Source Software",
    "Version Control Systems (Git, SVN)",
    "Code Quality and Testing",
    "Software Architecture and Design Patterns",
    "User Interface (UI) and User Experience (UX) Design",
    "Human-Computer Interaction (HCI)",
    "Responsive Web Design",
    "Progressive Web Apps (PWAs)",
    "Microservices Architecture",
    "Serverless Computing",
    "Edge Computing",
    "API Design and Integration",
    "Database Management Systems (SQL, NoSQL)",
    "Data Warehousing",
    "Data Science and Analytics",
    "Computer Vision",
    "Natural Language Generation (NLG)",
    "Edge AI",
    "Internet Security and Privacy Issues",
    "Biometric Authentication",
    "5G Technology",
    "Wi-Fi 6 and Networking Advances",
    "Robotics in Medicine and Healthcare",
    "Autonomous Vehicles",
    "Smart Cities and Urban Technology",
    "E-commerce Technology Trends",
    "Cryptocurrencies and Digital Wallets",
    "Gaming Technology and Trends",
    "Virtual Conferences and Events",
    "Social Media Algorithms",
    "Wearable Technology",
    "3D Printing",
    "Green Technology and Sustainability",
    "The Future of Work and Remote Collaboration Tools",
    "Tech Innovations in Education",
    "Accessibility in Technology",
    "Computational Biology",
    "Bioinformatics",
    "Precision Agriculture Technology",
    "Renewable Energy Technology",
    "Space Technology and Exploration",
    "Nanotechnology",
    "Smart Grid Technology",
    "Electronic Health Records (EHR)",
    "Telemedicine and Remote Healthcare",
    "3D Rendering and Animation",
    "Computer Graphics",
    "Quantum Cryptography",
    "Explainable AI (XAI)",
    "Ethical Considerations in Technology",
    "Tech and Social Justice",
    "Internet Censorship and Freedom",
    "Tech Entrepreneurship",
    "Venture Capital in the Tech Industry",
    "Tech Policy and Regulation",
    "Digital Transformation in Business",
    "Chatbots and Conversational AI",
    "Knowledge Graphs",
    "Augmented Data Management",
    "Biotechnology and Computational Genomics",
    "Cloud-Native Technologies",
    "Low-Code and No-Code Development",
    "Serverless Architecture",
    "IT Service Management (ITSM)",
    "Quantum Machine Learning",
    "Explainable AI (XAI)",
    "Edge AI Applications",
    "Cloud-Native Security",
    "Computational Photography",
    "Social Robotics",
    "Digital Twins",
    "Human Augmentation",
    "Explainable AI (XAI)",
    "Meta Platforms and the Metaverse",
    "Automated Content Moderation",
    "Edge Computing in Industrial IoT",
    "Tech and Mental Health",
    "Quantum Communication",
    "Future of Programming Languages",
    "Tech in Disaster Response",
    "Edge AI for Edge Computing",
    "Impact of Automation on Jobs",
    "Tech and Aging Population"
];




function SuffleTopic() {
    // random 
    let index = Math.floor(Math.random() * 100);

    topic.innerText = topicsArray[index];
}